name: Update Badges
on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
jobs:
  Generate-badges:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'
          ssh-known-hosts: 'github.ncsu.edu ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy5K6oZoBJ881aKKkon5MB016unAgciPVqNAlFY6PWtbUd7qJEwbJJAtxZcY43UmB8x4SW8yjqLGeQDEjioDkYY/Ml58Sh+gzAdeMeloGI2uwgVw77bGvcREAZ8s/lpx3D48XtvbS/IU4CgOO7RcMFsOH0y4jVX0LDdDxKLVXu/mUxnrqB8d/NtaZjOeI1b38LxFpfF6RVD7MBC9xhuZUcofVLQMhZq+OZ85xBxqb8UV5Ujp5hPbjO2uBDf3F1G0VLZko8W6LIiJaeBrEVl2UhQR2NDX5w7sUPg9D9mRWDQvIws1C887XeyF84cxkshFzuqbbtnGPVDxNpjMnDoWsN'
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - name: Generate coverage badges
        run: > 
            python3 .github/new_badges.py
      - name: Commit the badges
        run: |
          DETATCHED_HEAD_FOUND=$(git status | grep 'HEAD detached' | wc -l)
          if [[ `git status --porcelain` && $DETATCHED_HEAD_FOUND -eq 0 ]]; then
            git config --global user.name 'Badge Generator'
            git config --global user.email 'noemail-g83asgl510nfaeg04gsdf@ncsu.edu'
            git add -A
            git commit -m "Autogenerated badges"
            git push
          fi